/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BankImport } from './routes/$bank'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BankRoute = BankImport.update({
  id: '/$bank',
  path: '/$bank',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$bank': {
      id: '/$bank'
      path: '/$bank'
      fullPath: '/$bank'
      preLoaderRoute: typeof BankImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$bank': typeof BankRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$bank': typeof BankRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$bank': typeof BankRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$bank'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$bank'
  id: '__root__' | '/' | '/$bank'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$bank"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$bank": {
      "filePath": "$bank.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
